#!/bin/zsh

alias e='vim'

re() {
    e scp://$1/$2
}

function sess_path() {
    session=Session.vim

    if [ -d .git ]; then
        branch_name=$(git symbolic-ref -q HEAD)
        branch_name=${branch_name##refs/heads/}
        branch_name=${branch_name//\//_}
        session=.sessions/${branch_name:-Session}.vim
    fi

    echo "$session"
}

function es() {
    session="$(sess_path)"

    if [ -d .git ]; then
        if [ -f .sessions/_active ]; then
            echo "Can't start a new session because there is an existing session"
            return 1
        fi

        mkdir -p .sessions
        touch .sessions/_active
    fi

    local cmd=(vim)

    if [ -d .git ]; then
        cmd+=(-i .viminfo)
    fi

    if [ -f "$session" ]; then
        $cmd -S "$session" $@
    else
        $cmd -c "Obsession $session" $@
    fi

    if [ -d .sessions ]; then
        rm -f .sessions/_active
    fi
}

function res() {
    if [ -f .sessions/_active ]; then
        echo "Can't remove session file because it's in use"
        return 1
    fi

    rm -f "$(sess_path)"
    # Don't delete the info file - it's useful for history and marks etc.
}

function fes() {
    res && es $@
}
