#!/bin/zsh

alias ea='vim ~/.zsh_aliases && . ~/.zsh_aliases'
alias e='vim'

# Docker
alias doc=docker

# Git
alias ci='EDITOR="vim -c ShowDiff -c startinsert!" git ci'
alias ga='git add -p'

# Tmux
alias dev='start-agent && tm dev'
alias tmls='tmux ls'
tm() { tmux -u attach -t $1 || tmux -u new -s $1; }
alias tsb='tmux show-buffer'

# Vim
es() {
    if [ -f Session.vim ]; then
        vim -S Session.vim $@
    else
        vim -c 'Obsession' $@
    fi
}

res() {
    rm -f Session.vim
}

fes() {
    res && es $@
}

# Utils
alias c='clear'
alias hc='history -c'
alias ls='/opt/homebrew/bin/gls -lh --color=always --group-directories-first'
alias start-agent='eval `ssh-agent` && ssh-add'
alias stop-agent='killall ssh-agent'
alias py='python3'
catt() { cat $1; echo; }
nd() { mkdir -p $1; cd $1; }
